maps/urls.py
from django.urls import path
from . import views

app_name = 'maps'

urlpatterns = [
    path('VCB/', views.VCB, name="VCB"),
    path('api/geojson/branch/', views.branch_geojson, name='branch'),
    path('chat/message/', views.chat_api, name='chat_api'),
]

myproject/urls.py
# myproject/urls.py

from django.contrib import admin
from django.urls import path, include
from . import views  # <<< THÊM DÒNG NÀY VÀO
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage, name='homepage'), # Dòng này giờ sẽ không lỗi nữa
    path('gioi-thieu/', views.aboutpage, name='about'), # Đảm bảo views.aboutpage cũng tồn tại trong myproject/views.py
    path('maps/', include('maps.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/partials/footer.html
{% load static %}
<!DOCTYPE html>
<html class="no-js" lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <meta
      name="keywords"
      content="mobile banking, business consulting, bank loans, credit cards, finance, insurance, broker business, forex trading"
    />
    <meta
      name="description"
      content="Fibank – is a clean, modern and responsive design that let you to build an exclusive website for mobile banking, business consulting, bank loans, credit cards, finance, insurance, broker business, forex trading."
    />
    <title>Fibank - Banking And Finnance HTML5 Template</title>
    <meta property="og:site_name" content="Fibank" />
    <meta property="og:url" content="" />
    <meta property="og:type" content="website" />
    <meta
      property="og:title"
      content="Fibank - Banking And Finnance HTML5 Template"
    />
    <meta name="og:image" content="images/static/ogg.html" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="theme-color" content="#913BFF" />
    <meta name="msapplication-navbutton-color" content="#913BFF" />
    <meta name="apple-mobile-web-app-status-bar-style" content="#913BFF" />

    <link
      rel="shortcut icon"
      type="image/x-icon"
      href="{% static 'img2/favicon.png' %}"
    />
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}" />
    <link rel="stylesheet" href="{% static 'css/satoshi.css'%}" />
    <link rel="stylesheet" href="{% static 'fonts/bootstrap-icons.css'%}" />
    <link rel="stylesheet" href="{% static 'css/animate.min.css'%}" />
    <link rel="stylesheet" href="{% static 'css/slick.css'%}" />
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css'%}" />
    <link rel="stylesheet" href="{% static 'css/aos.css'%}" />
    <link rel="stylesheet" href="{% static 'css/spacing.css'%}" />
    <link rel="stylesheet" href="{% static 'css/main.css'%}" />
  </head>

  <body>
    <footer class="footer-five theme-bg2 mt--115 pt-195">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-xxl-6 col-xl-6 text-xl-start text-center">
            <div class="footer-widget">
              <div class="footer-logo">
                <a href="index.html"
                  ><img src="{% static 'img/logo/logo-2.svg'%}" alt="Logo"
                /></a>
              </div>
              <p class="description-text">
                Choose us for reliable, detail-oriented cleaning that meets all
                your cleanliness needs.
              </p>
              <ul class="d-md-flex justify-content-between">
                <li>
                  <a href="about.html">About us</a>
                </li>
                <li>
                  <a href="price.html">Pricing plan</a>
                </li>
                <li>
                  <a href="blog-grid.html">Blogs</a>
                </li>
                <li>
                  <a href="about.html">Testimonial</a>
                </li>
                <li>
                  <a href="contact.html">Contact us</a>
                </li>
              </ul>
            </div>
          </div>
          <div
            class="offset-xxl-1 col-xxl-5 col-xl-6 col-lg-7 text-center text-xl-end"
          >
            <h4 class="widget-title text-xl-start text-center">Newsletter</h4>
            <div
              class="subscribe-form sub-form-3 d-md-flex align-items-center mb-45"
            >
              <input type="text" placeholder="Enter Your Mail" />
              <button type="submit">Try Now</button>
            </div>
            <div class="social-links mb-5">
              <a href="#"><i class="bi bi-facebook"></i></a>
              <a href="#"><i class="bi bi-twitter"></i></a>
              <a href="#"><i class="bi bi-instagram"></i></a>
              <a href="#"><i class="bi bi-youtube"></i></a>
            </div>
          </div>
        </div>
      </div>
      <div class="container">
        <div class="copyright-wrap pt-30">
          <div class="row align-items-center">
            <div class="col-lg-6 col-md-6 text-center text-md-start">
              <div class="copyright-text pb-30">
                <a href="https://themeforest.net/user/creativegigs/portfolio"
                  >@ Powered By Fibank</a
                >
              </div>
            </div>
            <div class="col-lg-6 col-md-6 text-center text-md-end pb-30">
              <ul class="footer-menu">
                <li><a href="#">Terms & Conditions</a></li>
                <li><a href="#">Privacy Policy</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </footer>

    <script src="{% static 'js/modernizr-3.5.0.min.js'%}"></script>
    <script src="{% static 'js/jquery-3.5.1.min.js'%}"></script>
    <script src="{% static 'js/popper.min.js'%}"></script>
    <script src="{% static 'js/bootstrap.min.js'%}"></script>
    <script src="{% static 'js/jquery.meanmenu.js'%}"></script>
    <script src="{% static 'js/slick.min.js'%}"></script>
    <script src="{% static 'js/imagesloaded.pkgd.min.js'%}"></script>
    <script src="{% static 'js/isotope.pkgd.min.js'%}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js'%}"></script>
    <script src="{% static 'js/wow.min.js'%}"></script>
    <script src="{% static 'js/aos.js'%}"></script>
    <script src="{% static 'js/jquery.counterup.min.js'%}"></script>
    <script src="{% static 'js/jquery.waypoints.min.js'%}"></script>
    <script src="{% static 'js/jquery.easypiechart.min.js'%}"></script>
    <script src="{% static 'js/jquery-ui.js'%}"></script>

    <script src="{% static 'js/main.js'%}"></script>

    <script>
      /* magnificPopup video view */
      $(document).ready(function () {
        $(".popup-video").magnificPopup({
          type: "iframe",
        });
      });
    </script>

    {% comment %} <div class="templatecookie-btn">
      <a href="https://1.envato.market/e4QrVj" class="purchase-btn">
        Purchase Now
        <span>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            class="h-6 w-6"
            fill=""
            viewBox="0 0 24 24"
            stroke="currentColor"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 
                             0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z"
            />
          </svg>
        </span>
      </a>
    </div> {% endcomment %}
  </body>
</html>

templates/partials/header.html
{% load static %}
<!DOCTYPE html>
<html class="no-js" lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <meta
      name="keywords"
      content="mobile banking, business consulting, bank loans, credit cards, finance, insurance, broker business, forex trading"
    />
    <meta
      name="description"
      content="Fibank is a clean, modern and responsive design that let you to build an exclusive website for mobile banking, business consulting, bank loans, credit cards, finance, insurance, broker business, forex trading."
    />
    <title>Fibank - Banking And Finnance HTML5 Template</title>
    <meta property="og:site_name" content="Fibank" />
    <meta property="og:url" content="" />
    <meta property="og:type" content="website" />
    <meta
      property="og:title"
      content="Fibank - Banking And Finnance HTML5 Template"
    />
    <meta name="og:image" content="{% static 'img2/ogg.html' %}" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="theme-color" content="#913BFF" />
    <meta name="msapplication-navbutton-color" content="#913BFF" />
    <meta name="apple-mobile-web-app-status-bar-style" content="#913BFF" />

    <link
      rel="shortcut icon"
      type="image/x-icon"
      href="{% static 'img/favicon.png' %}"
    />
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}" />
    <link rel="stylesheet" href="{% static 'css/satoshi.css'%}" />
    <link rel="stylesheet" href="{% static 'fonts/bootstrap-icons.css'%}" />
    <link rel="stylesheet" href="{% static 'css/animate.min.css'%}" />
    <link rel="stylesheet" href="{% static 'css/slick.css'%}" />
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css'%}" />
    <link rel="stylesheet" href="{% static 'css/aos.css'%}" />
    <link rel="stylesheet" href="{% static 'css/spacing.css'%}" />
    <link rel="stylesheet" href="{% static 'css/main.css'%}" />
  </head>

  <body>
    <header class="theme-main-menu theme-menu-five">
      <div class="container-fluid custom-container">
        <div class="main-header-area">
          <div class="row align-items-center justify-content-between">
            <div class="col-md-auto col-6">
              <div class="logo-area">
                <a href="{% url 'homepage' %}">
                  <img
                    src="{% static 'img/logo/logo-1.svg' %}"
                    alt="Header-logo"
                  />
                </a>
              </div>
            </div>
            <div
              class="col-md-auto d-flex align-items-center justify-content-end d-lg-inline-block d-none"
            >
              <div class="main-menu d-none d-lg-block">
                <nav id="mobile-menu">
                  <ul class="menu-list">
                    <li>
                      <a href="/"> Home </a>
                      <ul class="sub-menu">
                        <li>
                          <a href="{% url 'maps:VCB' %}">Home Style 1</a>
                        </li>
                      </ul>
                    </li>
                    <li>
                      <a href="/"> Pages </a>
                      <ul class="sub-menu">
                        <li>
                          <a href="/">About Us</a>
                        </li>
                      </ul>
                    </li>
                    <li>
                      <a href="/">Service</a>
                      <ul class="sub-menu">
                        <li>
                          <a href="/">Services</a>
                        </li>
                        <li>
                          <a href="/">Services Details</a>
                        </li>
                      </ul>
                    </li>
                    <li>
                      <a href="/">Contact</a>
                    </li>
                  </ul>
                </nav>
              </div>
            </div>
            <div class="col-md-auto col-6">
              <div
                class="right-nav d-flex align-items-center justify-content-end"
              >
                <div class="cart-menu">
                  <a class="shopping-cart mr-20" href="#">
                    <i class="bi bi-bag"></i>
                    <span class="badge">0</span>
                  </a>
                </div>
                <div class="quote-btn d-lg-inline-block d-none">
                  <a
                    href="#"
                    class="ht-btn bs-btn"
                    data-bs-toggle="modal"
                    data-bs-target="#loginModal"
                    >Sign Up</a
                  >
                </div>
                <div class="search-area ms-1 d-none">
                  <a
                    class="search-input"
                    href="#"
                    data-bs-toggle="offcanvas"
                    data-bs-target="#offcanvasTop"
                    aria-controls="offcanvasTop"
                  >
                    <i class="bi bi-search"></i>
                  </a>
                </div>
                <div class="hamburger-menu ms-0 d-lg-none d-md-inline-flex">
                  <div class="bar-wrap">
                    <div class="bar-1"></div>
                    <div class="bar-2"></div>
                    <div class="bar-3"></div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </header>
    <main></main>
    <script src="{% static 'js/modernizr-3.5.0.min.js'%}"></script>
    <script src="{% static 'js/jquery-3.5.1.min.js'%}"></script>
    <script src="{% static 'js/popper.min.js'%}"></script>
    <script src="{% static 'js/bootstrap.min.js'%}"></script>
    <script src="{% static 'js/jquery.meanmenu.js'%}"></script>
    <script src="{% static 'js/slick.min.js'%}"></script>
    <script src="{% static 'js/imagesloaded.pkgd.min.js'%}"></script>
    <script src="{% static 'js/isotope.pkgd.min.js'%}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js'%}"></script>
    <script src="{% static 'js/wow.min.js'%}"></script>
    <script src="{% static 'js/aos.js'%}"></script>
    <script src="{% static 'js/jquery.counterup.min.js'%}"></script>
    <script src="{% static 'js/jquery.waypoints.min.js'%}"></script>
    <script src="{% static 'js/jquery.easypiechart.min.js'%}"></script>
    <script src="{% static 'js/jquery-ui.js'%}"></script>

    <script src="{% static 'js/main.js'%}"></script>

    <script>
      /* magnificPopup video view */
      $(document).ready(function () {
        $(".popup-video").magnificPopup({
          type: "iframe",
        });
      });
    </script>
    <div class="templatecookie-btn">
        <span>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            class="h-6 w-6"
            fill=""
            viewBox="0 0 24 24"
            stroke="currentColor"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 
                             0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z"
            />
          </svg>
        </span>
      </a>
    </div>
  </body>
</html>